export { default as JobInfoArea } from "./JobInfoArea/JobInfoArea"
export { default as Header } from "./Header/Header"
export { default as Footer } from "./Footer/Footer"
export { default as WorkSection } from "./WorkSection/WorkSection"
export { default as ConnectSection } from "./ConnectSection/ConnectSection"
